# Generated by Django 3.1.7 on 2021-07-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_auto_20210717_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
